- os: linux
  dist: trusty
  compiler: clang
  addons:
    apt:
      sources: 'llvm-toolchain-trusty-4.0'
      packages: ['clang-4.0']
  env:
    - COMPILER=clang++-4.0

language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install nose"
# command to run tests
script: 
  - env PYTHONPATH=$(echo ${PWD}) LD_LIBRARY_PATH=$(llvm-config --libdir) nosetests -v
